// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikx4c62dbzDST73P5pFgDzm8qxZUh3Hw',
    appId: '1:1069200075259:web:6f06b7c37d0717c0d3435e',
    messagingSenderId: '1069200075259',
    projectId: 'farmer-consumer-marketplace',
    authDomain: 'farmer-consumer-marketplace.firebaseapp.com',
    storageBucket: 'farmer-consumer-marketplace.firebasestorage.app',
    measurementId: 'G-3VV2LLHZ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrUID_sekEtWBGT-DPMUv_t4qURpPbLK4',
    appId: '1:1069200075259:android:3150a731548b10b6d3435e',
    messagingSenderId: '1069200075259',
    projectId: 'farmer-consumer-marketplace',
    storageBucket: 'farmer-consumer-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5F9phnmYLUY21r_B9RC8A2mLj-U7G0c',
    appId: '1:1069200075259:ios:63545aaeaac71ac9d3435e',
    messagingSenderId: '1069200075259',
    projectId: 'farmer-consumer-marketplace',
    storageBucket: 'farmer-consumer-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.farmerConsumerMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5F9phnmYLUY21r_B9RC8A2mLj-U7G0c',
    appId: '1:1069200075259:ios:63545aaeaac71ac9d3435e',
    messagingSenderId: '1069200075259',
    projectId: 'farmer-consumer-marketplace',
    storageBucket: 'farmer-consumer-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.farmerConsumerMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDikx4c62dbzDST73P5pFgDzm8qxZUh3Hw',
    appId: '1:1069200075259:web:07cfd392e7bdf30bd3435e',
    messagingSenderId: '1069200075259',
    projectId: 'farmer-consumer-marketplace',
    authDomain: 'farmer-consumer-marketplace.firebaseapp.com',
    storageBucket: 'farmer-consumer-marketplace.firebasestorage.app',
    measurementId: 'G-PQGNF9FX1T',
  );
}
